### PR TITLE
Add support for Motorola Moto G (falcon)

### PR DESCRIPTION
**Pull request by StandaSK**
Already sent upstream:
- V1: https://lore.kernel.org/lkml/f5d4d71cd59f25b80889ef88fa044aa3a4268d46.1711288736.git.stano.jakubek@gmail.com/T/#t
- V2: https://lore.kernel.org/lkml/32c507337ab80c550fb1df08f7014d1e31eb4c32.1711454680.git.stano.jakubek@gmail.com/T/#t
- V3: https://lore.kernel.org/lkml/32c507337ab80c550fb1df08f7014d1e31eb4c32.1712480582.git.stano.jakubek@gmail.com/T/#t

### CODE REVIEW

**Comment by StandaSK** [comment]
Should also enable tps65132 and tmp108 in defconfig, but I don't know how to do that

**Comment by z3ntu** [comment]
Great work!

Do you want me to wait to merge until this has also been accepted upstream, or get this in soonish?

**Comment by StandaSK** [comment]
Just sent a V3 with collected A-b/R-b, hopefully it'll get accepted soon. This can wait in the meantime.

**Comment by z3ntu** [comment]
Seems the patches were applied today: https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/log/?h=arm32-for-6.10

**Comment by StandaSK** [comment]
Yes, seems like it. So I guess this can now get merged.

**Review by z3ntu — APPROVED** [review]
Amazing, thanks!

**Pull request merged**
